// <auto-generated />
using System;
using LightController.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LightController.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "6.0.0-preview.5.21301.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LightController.Data.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ActivationToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c36ad5c2-3375-4de7-bd14-e4133fcb45d0",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedUserName = "Admin",
                            PasswordHash = "AQAAAAEAACcQAAAAEDZ9lr5Elalko2ZoXR7LPrymJYw/oXWrqDcl0pWhnSP8oLI3rfKUqI5/LsKUn89h9A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "04d23d09-e7e8-4cd1-859f-03b08fa2e8c4",
                            TwoFactorEnabled = false,
                            UserName = "Admin"
                        });
                });

            modelBuilder.Entity("LightController.Data.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("int");

                    b.Property<string>("RegisterNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Registered")
                        .HasColumnType("bit");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("StatusId");

                    b.ToTable("Devices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Device0",
                            RegisterNumber = "b526f582-7474-4caf-ade7-f9ae06e0bd57",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Device1",
                            RegisterNumber = "963bf2a9-0636-48a9-9368-7b69ebb5d430",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Device2",
                            RegisterNumber = "788d86b9-8b33-4024-b8bf-9a0516ac3a24",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "Device3",
                            RegisterNumber = "e09df482-3294-4029-9585-c66a5c9c87d7",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "Device4",
                            RegisterNumber = "db462502-1ba0-484f-b518-c2712bd8f489",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 6,
                            Name = "Device5",
                            RegisterNumber = "ae2610ad-641f-4837-966e-da80c0231b38",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 7,
                            Name = "Device6",
                            RegisterNumber = "7a318ae4-50f1-496c-9149-78d14973e91b",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 8,
                            Name = "Device7",
                            RegisterNumber = "b8cb3eaf-b144-480b-9d52-3d49fa7f9b45",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 9,
                            Name = "Device8",
                            RegisterNumber = "2a09d5d2-256a-4b64-83c3-3ed1fec48ce8",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 10,
                            Name = "Device9",
                            RegisterNumber = "9a588ca0-583a-4cb0-9a35-5d762193a412",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 11,
                            Name = "Device10",
                            RegisterNumber = "33cc61b9-ed4a-44d3-bb3a-0bbbf5b84cd2",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 12,
                            Name = "Device11",
                            RegisterNumber = "485a7247-66eb-4436-ba77-8f0c12caa211",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 13,
                            Name = "Device12",
                            RegisterNumber = "d621db22-a018-413f-adc2-39411094352a",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 14,
                            Name = "Device13",
                            RegisterNumber = "34aebbd7-b6f0-4879-8965-0e2bc61d8c14",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 15,
                            Name = "Device14",
                            RegisterNumber = "99bc853c-c0dc-4ad0-91e2-712f78a09a88",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 16,
                            Name = "Device15",
                            RegisterNumber = "295b6065-ed4e-467b-8771-1c55d9859856",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 17,
                            Name = "Device16",
                            RegisterNumber = "6e037ea3-c4b1-41e8-a6d1-3c5fbf2a18f2",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 18,
                            Name = "Device17",
                            RegisterNumber = "ea6e68f6-c437-4bef-8cdb-15756c62ae57",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 19,
                            Name = "Device18",
                            RegisterNumber = "563200f9-2e5a-43df-b001-d9e862bd6aa4",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 20,
                            Name = "Device19",
                            RegisterNumber = "c97836d0-61c4-4168-a454-347bf56438d3",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 21,
                            Name = "Device20",
                            RegisterNumber = "e8aeed35-fc90-485f-a109-f3f64b787d2c",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 22,
                            Name = "Device21",
                            RegisterNumber = "ba7f5a51-9fa6-4ca6-9e47-9579ae05c2c4",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 23,
                            Name = "Device22",
                            RegisterNumber = "c643e86f-0d1d-4e0d-810a-b6b1d29a8996",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 24,
                            Name = "Device23",
                            RegisterNumber = "22a51478-177c-4312-8986-16ef617defa3",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 25,
                            Name = "Device24",
                            RegisterNumber = "176c8ed4-971e-40b8-83e5-4609af11014c",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 26,
                            Name = "Device25",
                            RegisterNumber = "4d8c7573-629f-4092-b9e9-87d09d9f795b",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 27,
                            Name = "Device26",
                            RegisterNumber = "54d0ac5a-0854-4b92-b707-2056a42160a1",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 28,
                            Name = "Device27",
                            RegisterNumber = "fc52aab6-42a7-445f-9244-63c602098f85",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 29,
                            Name = "Device28",
                            RegisterNumber = "245124c9-4643-4932-ad3c-57d1c606d8f1",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 30,
                            Name = "Device29",
                            RegisterNumber = "aa91f270-b9be-4c40-9288-4e5541c1555a",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 31,
                            Name = "Device30",
                            RegisterNumber = "3b791439-e8c3-4657-b51f-ff4e2fc1a1bf",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 32,
                            Name = "Device31",
                            RegisterNumber = "9bfaa8e1-a5da-4b3b-9e26-30eadb7d4e23",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 33,
                            Name = "Device32",
                            RegisterNumber = "f2c46b3f-8fd0-4e5f-9dd8-5e04550b02ef",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 34,
                            Name = "Device33",
                            RegisterNumber = "60e164ad-e0d7-4855-bb81-cd65487ca333",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 35,
                            Name = "Device34",
                            RegisterNumber = "73896e3a-4929-49b8-a8ff-d8988068026b",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 36,
                            Name = "Device35",
                            RegisterNumber = "cbaee70a-edcd-471f-b89c-ac94f15952a3",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 37,
                            Name = "Device36",
                            RegisterNumber = "8eee957e-1903-4e41-816b-ff2e963a3701",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 38,
                            Name = "Device37",
                            RegisterNumber = "1926f781-896b-4a1e-bac6-fb331a779e1f",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 39,
                            Name = "Device38",
                            RegisterNumber = "0a164563-6641-414a-95a1-1ccdc71f6b4d",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 40,
                            Name = "Device39",
                            RegisterNumber = "184d43d6-f4b6-4f69-b9c9-8cf72e2de629",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 41,
                            Name = "Device40",
                            RegisterNumber = "94cb4a7b-9c36-417c-a4f9-da92426a7d69",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 42,
                            Name = "Device41",
                            RegisterNumber = "a8a8b2a5-615a-4838-80fe-ed9c433ab321",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 43,
                            Name = "Device42",
                            RegisterNumber = "19ae1930-d65c-4d5c-abde-314fa6f14a54",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 44,
                            Name = "Device43",
                            RegisterNumber = "0672f441-b959-4eff-b1b6-f1b05156d895",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 45,
                            Name = "Device44",
                            RegisterNumber = "896468ae-da31-480d-82c7-9dc8269a9154",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 46,
                            Name = "Device45",
                            RegisterNumber = "9ee2399b-7d94-47e6-96de-a3f7b517e6f3",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 47,
                            Name = "Device46",
                            RegisterNumber = "ac2123c0-4737-4ebd-a7c5-72b59ac2f2c4",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 48,
                            Name = "Device47",
                            RegisterNumber = "f204b326-77b1-4ef9-b472-325e309900de",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 49,
                            Name = "Device48",
                            RegisterNumber = "8195a9fa-198f-4662-80ac-eae31a901167",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 50,
                            Name = "Device49",
                            RegisterNumber = "e93abe6e-962e-46e8-9730-eafa66a4feb9",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 51,
                            Name = "Device50",
                            RegisterNumber = "a2bbf62a-d392-44ce-9f07-565f897d5764",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 52,
                            Name = "Device51",
                            RegisterNumber = "d3bd1916-ad30-4dce-a84e-0a29f48f233c",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 53,
                            Name = "Device52",
                            RegisterNumber = "7f139c9e-a846-41dd-a13d-6c6bbfd9a9de",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 54,
                            Name = "Device53",
                            RegisterNumber = "f8b8ed69-63fc-485e-802f-11c3f3e7f683",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 55,
                            Name = "Device54",
                            RegisterNumber = "4e59e445-267d-454a-8bb8-563d955952bf",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 56,
                            Name = "Device55",
                            RegisterNumber = "7bae7740-803c-4335-8544-0ff9080a99d7",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 57,
                            Name = "Device56",
                            RegisterNumber = "db805377-ab6f-49c3-b961-d85bb94dc4ce",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 58,
                            Name = "Device57",
                            RegisterNumber = "788714d2-0576-4643-a7ee-f6713e9a788f",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 59,
                            Name = "Device58",
                            RegisterNumber = "d1947d91-b018-46a4-88a8-652a84fb8ee6",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 60,
                            Name = "Device59",
                            RegisterNumber = "b9994700-156b-4fa9-89e3-765b1b40c723",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 61,
                            Name = "Device60",
                            RegisterNumber = "7804da73-106e-4b80-8583-ed2e2d2aa5aa",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 62,
                            Name = "Device61",
                            RegisterNumber = "1fc7f9ae-e180-4f60-a0cf-079bf49e908b",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 63,
                            Name = "Device62",
                            RegisterNumber = "f85e7f0f-2528-4ac5-83ac-1b87cb61b4c3",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 64,
                            Name = "Device63",
                            RegisterNumber = "852f91c2-9005-4818-8f73-7bc2eae2e202",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 65,
                            Name = "Device64",
                            RegisterNumber = "5ee5cafc-8bab-4eb3-a713-bd62ca4c5a3b",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 66,
                            Name = "Device65",
                            RegisterNumber = "72b8eb4c-0b33-4398-9932-9bcf055ded2b",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 67,
                            Name = "Device66",
                            RegisterNumber = "5e18d789-4e35-4887-85b9-57c4e9613e0f",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 68,
                            Name = "Device67",
                            RegisterNumber = "59be0fec-767a-404f-902d-9f1e96fc6e03",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 69,
                            Name = "Device68",
                            RegisterNumber = "2da8bf1c-0138-4606-9c11-1c1e75e66993",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 70,
                            Name = "Device69",
                            RegisterNumber = "61be70d9-1258-435e-bcaf-59fbf6308b0e",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 71,
                            Name = "Device70",
                            RegisterNumber = "285a2b61-7e04-4e58-bc37-454110158dff",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 72,
                            Name = "Device71",
                            RegisterNumber = "7d16d86a-b702-49f0-951a-46f731d9347c",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 73,
                            Name = "Device72",
                            RegisterNumber = "7118c2af-7801-49fc-9253-48706867026c",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 74,
                            Name = "Device73",
                            RegisterNumber = "ca45c0aa-6ffa-401f-a679-0913a9d0a9f8",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 75,
                            Name = "Device74",
                            RegisterNumber = "174fdfad-593d-451a-8385-01d8493b8649",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 76,
                            Name = "Device75",
                            RegisterNumber = "1167c2e8-47b2-409a-a0ef-045f526c98fc",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 77,
                            Name = "Device76",
                            RegisterNumber = "d2eb17ef-1b3e-4661-a74c-69d456919f91",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 78,
                            Name = "Device77",
                            RegisterNumber = "fb065b53-6634-40b6-8ae6-889774d4b474",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 79,
                            Name = "Device78",
                            RegisterNumber = "2f4ae626-1032-4554-a63c-759717999827",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 80,
                            Name = "Device79",
                            RegisterNumber = "6fc70e10-d405-43ab-b3b1-59267cb56dda",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 81,
                            Name = "Device80",
                            RegisterNumber = "70927531-4d0e-4ae0-b09c-48279e98df7d",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 82,
                            Name = "Device81",
                            RegisterNumber = "550ead09-3984-4e71-b0e6-4028ba0e7948",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 83,
                            Name = "Device82",
                            RegisterNumber = "ffd4df3b-ded4-4e1c-ae19-cb288623c749",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 84,
                            Name = "Device83",
                            RegisterNumber = "26aae4f7-b286-4358-a450-840cc1cf116a",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 85,
                            Name = "Device84",
                            RegisterNumber = "42397f15-e3fa-4c4b-b4da-905c87eb9398",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 86,
                            Name = "Device85",
                            RegisterNumber = "2fbfc621-2898-45bc-963c-b632a3c1f693",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 87,
                            Name = "Device86",
                            RegisterNumber = "077eaeaf-5ab8-437e-9657-928825764d13",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 88,
                            Name = "Device87",
                            RegisterNumber = "d5108938-62f9-4068-891b-e578fbb74fb5",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 89,
                            Name = "Device88",
                            RegisterNumber = "c73c91de-92ee-45a8-a0ce-f4c9db3d0e7e",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 90,
                            Name = "Device89",
                            RegisterNumber = "963aaab1-d6ce-454b-bfeb-3cde10e31e91",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 91,
                            Name = "Device90",
                            RegisterNumber = "11d4db88-0353-4537-9fe0-504737f77b38",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 92,
                            Name = "Device91",
                            RegisterNumber = "da5c0072-7e7c-4463-9f0b-86173e50a233",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 93,
                            Name = "Device92",
                            RegisterNumber = "e6cd943f-8ad3-479b-b407-1a661a637c59",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 94,
                            Name = "Device93",
                            RegisterNumber = "fc012b18-f3ef-44dc-a347-296ac434530c",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 95,
                            Name = "Device94",
                            RegisterNumber = "145e3f4d-1322-45f1-8de2-2b6813d206e3",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 96,
                            Name = "Device95",
                            RegisterNumber = "d3e1bd94-97a5-4b53-b940-9dc840754c67",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 97,
                            Name = "Device96",
                            RegisterNumber = "63041afb-35d7-4cd6-be38-19cbdcd83854",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 98,
                            Name = "Device97",
                            RegisterNumber = "d13a38eb-1c0b-44cb-903a-1e529d5ab56b",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 99,
                            Name = "Device98",
                            RegisterNumber = "b81680d8-9c89-4825-a12e-59efb9c64460",
                            Registered = false,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 100,
                            Name = "Device99",
                            RegisterNumber = "68a8d1e5-5ca5-486a-bf14-e9b21361a191",
                            Registered = false,
                            StatusId = 1
                        });
                });

            modelBuilder.Entity("LightController.Data.Function", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Driver")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Functions");
                });

            modelBuilder.Entity("LightController.Data.FunctionList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DeviceId")
                        .HasColumnType("int");

                    b.Property<int?>("FunctionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("FunctionId");

                    b.ToTable("FunctionLists");
                });

            modelBuilder.Entity("LightController.Data.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ExpirationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Used")
                        .HasColumnType("bit");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("LightController.Data.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "",
                            Name = "Wyłączony"
                        },
                        new
                        {
                            Id = 2,
                            Description = "",
                            Name = "Włączony"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "ef3ca424-f6fb-4975-a35b-d5eb9cb0f25d",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("LightController.Data.Device", b =>
                {
                    b.HasOne("LightController.Data.ApplicationUser", "Owner")
                        .WithMany("Devices")
                        .HasForeignKey("OwnerId");

                    b.HasOne("LightController.Data.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("LightController.Data.FunctionList", b =>
                {
                    b.HasOne("LightController.Data.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId");

                    b.HasOne("LightController.Data.Function", "Function")
                        .WithMany()
                        .HasForeignKey("FunctionId");

                    b.Navigation("Device");

                    b.Navigation("Function");
                });

            modelBuilder.Entity("LightController.Data.PasswordResetToken", b =>
                {
                    b.HasOne("LightController.Data.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("LightController.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("LightController.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LightController.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("LightController.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LightController.Data.ApplicationUser", b =>
                {
                    b.Navigation("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
